/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: 526c7e17f434f814990223dbd9a633a9)
interface __BaseEnv_Env {
  DB: D1Database;
  VAPID_SUBJECT: "https://personal-tools.surge.sh";
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY: string;
  SETUP_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "VAPID_SUBJECT" | "VAPID_PUBLIC_KEY" | "VAPID_PRIVATE_KEY" | "SETUP_KEY"
    >
  > {}
}
